### ISSUE TITLE
Document how timestampmaker can help the ChRIS Project

### ISSUE THREAD

**Issue by computate** [rh-impact/pnt-hackathon-2022#35]
Create a README.adoc file in the new pl-timestampmaker in the rh-impact Github organization created in an earlier task to document in asciidoc the overview and parameters that can be used to perform timestampmaker operations for the ChRIS project.

http://chrisproject.org/
http://chrisproject.org/for-devs

**Comment by olivelakra** [comment]
Draft content added to README.rst file to 'docs' branch. Need to review and merge to Master.
https://github.com/rh-impact/pl-timestampmaker/tree/docs

@barbacbd @cbbm142

**Comment by olivelakra** [comment]
Pull request added.
https://github.com/rh-impact/pl-timestampmaker/pull/2

**Comment by olivelakra** [comment]
Task completed

**Comment by GeoEducator** [comment]
Ok
