### ISSUE TITLE
Document how matplotlib can help the ChRIS Project

### ISSUE THREAD

**Issue by computate** [rh-impact/pnt-hackathon-2022#48]
Create a README.adoc file in the new pl-matplotlib repo in the rh-impact Github organization created in an earlier task to document in asciidoc the overview and parameters that can be used to perform matplotlib operations for the ChRIS project.

http://chrisproject.org/
http://chrisproject.org/for-devs

**Comment by xtmprsqzntwlfb** [comment]
PR accepted: https://github.com/rh-impact/pl-matplotlib/pull/1
