### ISSUE TITLE
Document how ffmpeg can help the ChRIS Project

### ISSUE THREAD

**Issue by computate** [rh-impact/pnt-hackathon-2022#62]
Create a README.adoc file in the new pl-ffmpeg repo in the rh-impact Github organization created in an earlier task to document in asciidoc the overview and parameters that can be used to perform ffmpeg operations for the ChRIS project.

http://chrisproject.org/
http://chrisproject.org/for-devs

**Comment by ozanunsal** [comment]
It will be handled in PR: https://github.com/rh-impact/pl-ffmpeg/pull/1
