### ISSUE TITLE
Create a pl-graphicsmagick repo in the rh-impact organization repos

### ISSUE THREAD

**Issue by computate** [rh-impact/pnt-hackathon-2022#63]

**Comment by adithyaakrishna** [comment]
Created a new one at, https://github.com/rh-impact/pl-graphicsmagick

**Comment by jistr** [comment]
@adithyaakrishna can you give me co-ownership of the repo please? We can't clone it until there is some content. I have it prepared to push the initial state based on https://github.com/FNNDSC/python-chrisapp-template (hopefully preserving its commit history too).

**Comment by adithyaakrishna** [comment]
Closed as the repo is created :)
