### ISSUE TITLE
Document how graphicsmagick can help the ChRIS Project

### ISSUE THREAD

**Issue by computate** [rh-impact/pnt-hackathon-2022#64]
Create a README.adoc file in the new pl-graphicsmagick repo in the rh-impact Github organization created in an earlier task to document in asciidoc the overview and parameters that can be used to perform graphicsmagick operations for the ChRIS project.

http://chrisproject.org/
http://chrisproject.org/for-devs

**Comment by jistr** [comment]
The plugin is documented in the readme :book:  https://github.com/rh-impact/pl-graphicsmagick/blob/main/README.md
