### ISSUE TITLE
Create a pl-gimic repo in the rh-impact organization repos

### ISSUE THREAD

**Issue by computate** [rh-impact/pnt-hackathon-2022#69]

**Comment by adithyaakrishna** [comment]
Created a new one at, https://github.com/rh-impact/pl-gimic

**Comment by parth-gr** [comment]
@adithyaakrishna I don't we have clone or fork access in the repo, please provide

**Comment by adithyaakrishna** [comment]
Done 💯

**Comment by adithyaakrishna** [comment]
Closed as the repo is created :)
