### ISSUE TITLE
Document how heudiconv can help the ChRIS Project

### ISSUE THREAD

**Issue by grdryn** [rh-impact/pnt-hackathon-2022#76]
Create a README.adoc file in the new pl-heudiconv repo in the rh-impact Github organization created in an earlier task to document in asciidoc the overview and parameters that can be used to perform heudiconv operations for the ChRIS project.

http://chrisproject.org/
http://chrisproject.org/for-devs

**Comment by bredamc** [comment]
First draft in progress here: https://github.com/rh-impact/pl-heudiconv/pull/6

**Comment by grdryn** [comment]
Thanks a lot @bredamc, I've merged that now as it's a useful change as-is. We can iteratively improve it over time, rather than holding that open waiting for it to be perfect. It's also good to have it as some completed progress now as the hackathon draws to a close—we can close this task, and create any follow-up tasks in the rh-impact/pl-heudiconv repo itself if needed.

It has been a pleasure working with you on this team in the hackathon! 🙂

**Comment by bredamc** [comment]
Many thanks for all your help @grdryn! It's been a pleasure to work with you too -- I learned so much from you! :)
